### PR TITLE
PEER REVIEW : desilva/authentication

### PR DESCRIPTION
**Pull request by tharakadesilva**

### CODE REVIEW

**Comment by winterdharma** [comment]
What happened with schema.rb?

**Comment by tharakadesilva** [comment]
@winterdharma fixed

**Comment by winterdharma** [comment]
I'm still confused with the changes to the DB. You have a Users table in Structure.sql and a migration that creates a Users table. You could alter the Users table with the migration or just change the Structure.sql, but doing both should cause some kind of mysql conflict?

**Comment by tharakadesilva** [comment]
I have commented out the creation of the user table in the structure.sql file. The users table is now created through the migration. I have to add some fields from the structures.sql to the migration in the next sprint. I left the portion in the structures.sql as a reference to add to the migration. Also, since we are using migrations, I shall work on converting the structures.sql file into a migration as well. We might have to modify the ERD a bit.

**Comment by winterdharma** [comment]
I see. Okay. Looks good otherwise.

**Pull request merged**
